# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.

"""Schemas for the ``analysis/`` directory shared by the report and dashboard
subagents.

The visual report / dashboard artifacts grow an ``analysis/`` subdirectory
alongside ``queries/`` and ``render/``:

* ``analysis/intent.md`` — raw user prompts, append-only. Plain markdown,
  no Pydantic model — just a list of timestamped ``> ...`` blockquote
  sections.
* ``analysis/interpretation.json`` — :class:`Interpretation`. The LLM's
  structured read of ``intent.md`` (audience / goal / focus_questions).
  Full rewrite on every finalize.
* ``analysis/insights.json`` — ``List[Insight]``. Confirmed findings.
  **Report only.** Dashboard data is materialized at runtime, so there
  are no pre-baked conclusions to surface.
* ``analysis/suggested_questions.json`` — ``List[SuggestedQuestion]``.
  Exactly 5 follow-up questions. Both kinds.
* ``analysis/subject_refs.json`` — :class:`SubjectRefs`. Snapshot of
  every subject-library asset (metric / reference_sql / ext_knowledge)
  any ``queries/<name>.reasoning.json`` declared in its ``uses`` block.
  Generated by code, not by the LLM (the LLM declares ``uses`` at
  ``save_query`` time when it's most knowledgeable; code aggregates).
* ``queries/<name>.reasoning.json`` — :class:`ReasoningStep`. Per-query
  metadata (goal / hypothesis / uses / caveats) written by the LLM the
  moment it calls ``save_query`` / ``save_query_template``.

Cross-file references are strictly one-directional from fine-grained
objects to coarse ones (or to subject-library ids) — see
``docs/analysis_artifacts.md`` for the full reference graph and the
rationale for not storing reverse indexes.
"""

from __future__ import annotations

import re
from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

# Same character set as ``REPORT_SLUG_RE`` / ``QUERY_SLUG_RE`` so insight
# ids and subject-asset ids stay filesystem-friendly and easy to ``grep``
# from compiled HTML output. Length cap matches QUERY_SLUG_RE; insight
# slugs are LLM-chosen identifiers, not paths.
ANALYSIS_SLUG_PATTERN = r"^[a-z0-9_]{1,64}$"
ANALYSIS_SLUG_RE = re.compile(ANALYSIS_SLUG_PATTERN)

SubjectAssetKind = Literal["metric", "reference_sql", "ext_knowledge"]


class SubjectRefIds(BaseModel):
    """Per-query declaration of which subject-library assets a query draws on.

    Stored inline on :class:`ReasoningStep`. Three buckets matching the
    three asset kinds Datus' subject library exposes today; future kinds
    can be added without breaking older reasoning files because each
    bucket defaults to an empty list.

    The LLM is the only producer — it fills these arrays at
    ``save_query`` time when it knows exactly which metric / reference
    SQL / ext-knowledge entry informed the query it's about to persist.
    Empty arrays are valid and common (many queries are pure ad-hoc
    SELECTs against the base tables).
    """

    model_config = ConfigDict(extra="forbid")

    metrics: List[str] = Field(
        default_factory=list,
        description="Metric ids (semantic-model entries) that informed this query's design.",
    )
    reference_sql: List[str] = Field(
        default_factory=list,
        description="Reference-SQL ids the query borrows shape / patterns from.",
    )
    ext_knowledge: List[str] = Field(
        default_factory=list,
        description="Ext-knowledge entry ids consulted for definitions, thresholds, business rules.",
    )


class ReasoningStep(BaseModel):
    """Schema for ``queries/<name>.reasoning.json``.

    Sits next to ``<name>.sql`` / ``<name>.json`` (report) or
    ``<name>.sql.j2`` / ``<name>.params.json`` (dashboard) — three- or
    four-file query bundles depending on artifact kind. Written atomically
    by ``save_query`` / ``save_query_template`` in the same call that
    persists the SQL itself, so a query bundle is always complete or
    completely absent.

    Write-once-overwrite (no append): rerunning a same-named query
    replaces its reasoning file alongside its SQL and JSON files. History
    lives in git, not inside the file.
    """

    model_config = ConfigDict(extra="forbid")

    name: str = Field(
        ...,
        pattern=ANALYSIS_SLUG_PATTERN,
        description="Query slug, matches the sibling ``<name>.sql`` filename.",
    )
    goal: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description=(
            "The research question this query answers — open-ended, e.g. "
            "'distribution of high-risk signups across months'. Becomes the "
            "first SQL comment line for IDE hover, mirroring the legacy "
            "``description`` arg."
        ),
    )
    hypothesis: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description=(
            "One-sentence concrete prediction the LLM expects this query to "
            "validate or refute (e.g. 'high-risk signups cluster around "
            "promotional campaigns'). Empty / placeholder text is rejected "
            "to keep the field substantive — the system prompt instructs the "
            "LLM to skip the query rather than write filler here."
        ),
    )
    uses: SubjectRefIds = Field(
        default_factory=SubjectRefIds,
        description="Subject-library assets this query draws on (three buckets).",
    )
    caveats: str = Field(
        default="",
        max_length=500,
        description=(
            "Empty by default. Filled only when this query makes a "
            "non-obvious choice a future reader would otherwise miss: "
            "non-standard join, outlier filtering, weighted vs simple avg, "
            "etc. The system prompt explicitly tells the LLM NOT to use "
            "this for routine commentary."
        ),
    )
    datasource: str = Field(
        ...,
        description=(
            "Resolved datasource label this query was run against — copied "
            "from the ``save_query`` call so ``analysis/subject_refs.json`` "
            "aggregation can preserve datasource context even if the global "
            "config later changes the default."
        ),
    )
    created_at: str = Field(..., description="ISO-8601 UTC timestamp at second precision.")


class Interpretation(BaseModel):
    """Schema for ``analysis/interpretation.json``.

    The LLM's structured read of the raw prompts in ``intent.md``.
    Written once at the end of the finalize step and rewritten in full
    on every edit-mode finalize.

    Deliberately small — see ``docs/analysis_artifacts.md`` §3.4 for
    fields we explicitly chose NOT to include (hypotheses, tags,
    based_on_prompts, …).
    """

    model_config = ConfigDict(extra="forbid")

    audience: List[str] = Field(
        ...,
        min_length=1,
        description="Who the artifact is for, e.g. ['Ops managers'] — drives tone of generated insights / suggested follow-ups.",
    )
    goal: str = Field(
        ...,
        min_length=1,
        max_length=600,
        description="One-sentence framing of what the artifact is supposed to help its audience accomplish.",
    )
    focus_questions: List[str] = Field(
        ...,
        min_length=1,
        description="Concrete questions the artifact tries to answer. Frontend renders these; LLM finalize step uses them to anchor suggested follow-ups.",
    )
    last_updated: str = Field(..., description="ISO-8601 UTC of the most recent finalize that wrote this file.")


class Insight(BaseModel):
    """One confirmed finding.

    Used in ``List[Insight]`` for ``analysis/insights.json``. **Report
    only**: dashboard queries are runtime-rendered templates, so there
    are no statically-known conclusions to encode here.

    Insights cite queries (``evidence_queries``) and may cite ext-knowledge
    entries (``informed_by_knowledge``) but never cite intent.md (which
    has no stable anchor ids — see docs §6).
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(
        ...,
        pattern=ANALYSIS_SLUG_PATTERN,
        description="LLM-chosen semantic slug; referenced by ``SuggestedQuestion.related_insight``.",
    )
    title: str = Field(..., min_length=1, max_length=200)
    summary: str = Field(..., min_length=1, max_length=1000, description="1–3 sentences stating the finding plainly.")
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM-estimated confidence in [0,1]. Frontend uses it for ranking; subagent uses it as a hedging signal when answering follow-ups.",
    )
    evidence_queries: List[str] = Field(
        ...,
        min_length=1,
        description="Query slugs (matching ``queries/<name>.*`` filenames) that back this finding.",
    )
    informed_by_knowledge: List[str] = Field(
        default_factory=list,
        description="Optional ext-knowledge entry ids that shaped the interpretation.",
    )


class SuggestedQuestion(BaseModel):
    """One follow-up suggestion shown to the user as a quick-action chip.

    Used in ``List[SuggestedQuestion]`` for
    ``analysis/suggested_questions.json``. Both report and dashboard
    produce these — dashboards just keep ``related_insight=None``
    (there are no insights to anchor to).
    """

    model_config = ConfigDict(extra="forbid")

    question: str = Field(
        ...,
        min_length=1,
        max_length=300,
        description="Single-sentence follow-up. Same language as the user's prompts where possible.",
    )
    related_queries: List[str] = Field(
        default_factory=list,
        description="Query slugs the suggestion would build on.",
    )
    related_insight: Optional[str] = Field(
        default=None,
        description=(
            "Insight slug this follow-up extends. Report-only; dashboards always set "
            "this to ``None`` since there are no insights for them."
        ),
    )
    priority: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM-assigned priority in [0,1]; frontend uses it for display order when more than one suggestion competes for the same slot.",
    )


class SubjectAssetRef(BaseModel):
    """One entry inside :class:`SubjectRefs` — the snapshot of a single
    subject-library asset referenced anywhere in this artifact.

    These snapshots are the fallback when the global subject library has
    moved on (asset renamed or deleted): the subagent can still answer
    "what is metric X" by reading ``definition_or_summary`` straight from
    the snapshot. We deliberately do not store version hashes — see
    docs §3.7.
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(..., description="Stable id within the subject library (metric id / reference_sql id / kb id).")
    name: str = Field(
        ...,
        description=(
            "Human-readable name copied from the subject library at finalize time. "
            "For ext_knowledge entries this is the document title."
        ),
    )
    definition_or_summary: str = Field(
        default="",
        description=(
            "Snapshot of the asset body: SQL expression for metrics, query text for "
            "reference_sql, a short summary for ext_knowledge. Empty when the "
            "subject library lookup failed (id was made up or has since been "
            "removed) — the aggregation step logs a warning but keeps the entry "
            "so the subagent still sees that this id was referenced."
        ),
    )
    source: str = Field(
        default="",
        description=(
            "Path inside ``subject/`` where this asset lives, when known. Empty "
            "string when not resolvable (same fallback semantics as "
            "``definition_or_summary``)."
        ),
    )


class SubjectRefs(BaseModel):
    """Schema for ``analysis/subject_refs.json`` — the leaf node of the
    reference graph (nothing references *it* by id; it's the index the
    subagent reads to render asset cards).

    Generated by code, not the LLM: ``finalize`` enumerates every
    ``queries/*.reasoning.json``, collects each ``uses`` bucket, dedupes
    by id, looks each id up in the subject library to snapshot
    ``name`` / ``definition_or_summary`` / ``source``, and writes this
    file last. See docs §3.7.
    """

    model_config = ConfigDict(extra="forbid")

    metrics: List[SubjectAssetRef] = Field(default_factory=list)
    reference_sql: List[SubjectAssetRef] = Field(default_factory=list)
    ext_knowledge: List[SubjectAssetRef] = Field(default_factory=list)


class FinalizeAnalysisOutput(BaseModel):
    """The schema the finalize-stage LLM call must produce in a single shot.

    Aggregates the three LLM-authored analysis files (interpretation,
    insights, suggested_questions). ``subject_refs`` is built by code
    afterwards, so it's NOT part of this schema — keeping LLM output
    narrow makes structured-output mode more reliable.

    Dashboards set ``insights=[]`` because their data is runtime-only
    (see docs §3.5). The finalize prompt makes that explicit and the
    node-level validation enforces it for dashboard runs.
    """

    model_config = ConfigDict(extra="forbid")

    interpretation: Interpretation
    insights: List[Insight] = Field(
        default_factory=list,
        description="Empty for dashboard artifacts; 3–8 entries typical for reports.",
    )
    suggested_questions: List[SuggestedQuestion] = Field(
        ...,
        min_length=1,
        max_length=8,
        description="Target is exactly 5. We allow 1–8 so a marginal LLM run isn't rejected outright.",
    )
