workflow:

  reflection:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  fixed:
    - schema_linking
    - generate_sql
    - execute_sql
    - output

  empty: []

  dynamic:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  metric2SQL:
<<<<<<< HEAD
=======
    - schema_linking
>>>>>>> 1027f39 (search_metric node & its workflow)
    - search_metrics
    - generate_sql
    - execute_sql
    - output
