name: "main"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  title-check:
    uses: ./.github/workflows/pr-title-checker.yml
  format-check:
    needs: title-check
    uses: ./.github/workflows/python-format-check.yml
  run-ut:
    needs: format-check
    uses: ./.github/workflows/run-ut.yml
