name: unit test
on:
  workflow_call:
    outputs:
      build-artifact:
        description: "Built artifact path"
        value: ${{ jobs.build.outputs.build-artifact }}

jobs:
  run-ut:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup config file
        run: |
          cp /home/datus_ci/ci_template/agent.yml conf/agent.yml
          cp /home/datus_ci/ci_template/ci.env .env

      - name: Load environment variables
        run: |
          echo "Loading environment variables from .env file..."
          # Export all variables from .env to GITHUB_ENV so they persist across steps
          while IFS= read -r line || [ -n "$line" ]; do
            # Skip empty lines and comments
            if [[ ! -z "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
              # Remove any surrounding whitespace and export to GITHUB_ENV
              var_name=$(echo "$line" | cut -d'=' -f1)
              echo "Loading variable: $var_name"
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env
          echo "Environment variables loaded successfully"

      - name: Build test data
        run: |
          echo "Building test data before running pytest..."
          chmod +x build_scripts/build_test_data.sh
          ./build_scripts/build_test_data.sh
          echo "Test data build completed"

      - name: run pytest
        run: |
          python -m pytest -m acceptance  tests/
